# Generated by Django 5.1.3 on 2024-12-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise_name',
            field=models.CharField(max_length=255),
        ),
    ]
