# Generated by Django 5.1.3 on 2025-01-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_log', '0002_alter_exerciselog_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciselog',
            old_name='repetition_count',
            new_name='repetitions',
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='exercise_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exerciselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_log_exercise_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
