# Generated by Django 5.1.3 on 2024-12-24 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_exerciselog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExerciseLog',
        ),
    ]
